language: python
python:
  - "3.6.2"
  
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - pip install coveralls
  - pip install coverage
script:
  - "python test_member.py"
  - "python test_recipe.py"
  - "coverage run test_member.py"
  - "coverage run test_recipe.py"
after_success:
  - coveralls
notifications:
  email: false