language: python
python:
  - "3.6.2"
  
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - pip install coveralls
script:
  - "pytest"
  - coverage run pytest
after_success:
  - coveralls
notifications:
  email: false