language: python
python:
  - "3.6.2"
  
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - pip install coveralls
script:
  - "python test_users.py"
  - "python test_recipes.py"
  - "coverage run test_users.py"
  - "coverage run test_recipes.py"
after_success:
  - coveralls
notifications:
  email: false
